# lightGBM으로 예측

In [1]:
from lightgbm import LGBMClassifier

from encodings import euc_kr
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
f=pd.read_csv('f_rf.csv', encoding='euc_kr')
for i in range(f.shape[0]):
    if f.iloc[i,-1]=='상승':
        f.iloc[i,-1]=1
    else:
        f.iloc[i,-1]=0

In [3]:
f.columns=['0', '1', '2', '3', '4', '5', '6',
       '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21',
       '22', '23', '24', '25', '26', '27', '28', '29', '30',
       'oil', '31', '32', 'USD', 'EUR', 'CNY', 'JPY', 'GBP', 'Y']

In [6]:
X_train.head()

1        2         3          4        5         6      7           8  \
0  520.95  1223328  19638887  191252891  2723222  58238292  746.0  20010102.0   
1  521.43  1583403  19633559  191363161  2727918  58249739  746.0  20010102.0   
2  558.02  2984761  19634734  204074166  2735566  62823637  746.0  20010102.0   
3  580.85  3569582  19637038  212089180  2747453  65820417  746.0  20010103.0   
4  586.65  2948092  19630735  214231273  2751599  66348238  746.0  20010104.0   

     9   10  ...     29      30   oil   31    32     USD      EUR     CNY  \
0  704  853  ...  270.6  7202.5  25.8  8.5  11.9  1259.7  1185.38  152.19   
1  704  854  ...  267.5  6641.3  26.5  8.6  11.8  1267.8  1205.49  153.15   
2  704  855  ...  267.7  6843.0  26.8  8.3  11.4  1285.4  1193.24  155.29   
3  704  855  ...  268.2  6878.7  26.6  8.0  11.0  1249.3  1190.90  150.92   
4  704  854  ...  268.3  7012.1  25.8  8.0  10.9  1267.8  1215.06  153.16   

       JPY      GBP  
0  1099.07  1885.02  
1  1108.07  1903.35  
2  1128.53  1914.15  
3  1078.01  1876.82  
4  1088.71  1906.33  

[5 rows x 38 columns]

In [5]:

X_train=f.iloc[0:3962,1:-1]
X_test=f.iloc[3962:,1:-1]
y_train=f.iloc[0:3962,-1]
y_test=f.iloc[3962:,-1]

lgbm_wrapper = LGBMClassifier(n_estimators=500, learning_rate=0.001, booster='rf', max_depth=3, num_leaves=90)

# LightGBM도 XGBoost와 동일하게 조기 중단 수행 가능. 
evals = [(X_test, y_test)]
lgbm_wrapper.fit(X_train, y_train, early_stopping_rounds=250, eval_metric="logloss", 
                 eval_set=evals,verbose=True)
preds = lgbm_wrapper.predict(X_test)

[1]	valid_0's binary_logloss: 0.68786
Training until validation scores don't improve for 250 rounds
[2]	valid_0's binary_logloss: 0.687865
[3]	valid_0's binary_logloss: 0.68787
[4]	valid_0's binary_logloss: 0.687875
[5]	valid_0's binary_logloss: 0.68788
[6]	valid_0's binary_logloss: 0.687885
[7]	valid_0's binary_logloss: 0.687891
[8]	valid_0's binary_logloss: 0.687897
[9]	valid_0's binary_logloss: 0.687902
[10]	valid_0's binary_logloss: 0.687908
[11]	valid_0's binary_logloss: 0.687914
[12]	valid_0's binary_logloss: 0.687921
[13]	valid_0's binary_logloss: 0.687927
[14]	valid_0's binary_logloss: 0.687934
[15]	valid_0's binary_logloss: 0.68794
[16]	valid_0's binary_logloss: 0.687947
[17]	valid_0's binary_logloss: 0.687954
[18]	valid_0's binary_logloss: 0.687962
[19]	valid_0's binary_logloss: 0.687969
[20]	valid_0's binary_logloss: 0.687976
[21]	valid_0's binary_logloss: 0.687984
[22]	valid_0's binary_logloss: 0.687992
[23]	valid_0's binary_logloss: 0.688
[24]	valid_0's binary_logloss: 0.6

[217]	valid_0's binary_logloss: 0.691433
[218]	valid_0's binary_logloss: 0.691449
[219]	valid_0's binary_logloss: 0.691469
[220]	valid_0's binary_logloss: 0.691496
[221]	valid_0's binary_logloss: 0.691513
[222]	valid_0's binary_logloss: 0.691532
[223]	valid_0's binary_logloss: 0.69156
[224]	valid_0's binary_logloss: 0.691587
[225]	valid_0's binary_logloss: 0.691604
[226]	valid_0's binary_logloss: 0.691623
[227]	valid_0's binary_logloss: 0.69164
[228]	valid_0's binary_logloss: 0.69166
[229]	valid_0's binary_logloss: 0.691687
[230]	valid_0's binary_logloss: 0.691704
[231]	valid_0's binary_logloss: 0.691724
[232]	valid_0's binary_logloss: 0.691752
[233]	valid_0's binary_logloss: 0.691779
[234]	valid_0's binary_logloss: 0.691796
[235]	valid_0's binary_logloss: 0.691816
[236]	valid_0's binary_logloss: 0.691834
[237]	valid_0's binary_logloss: 0.691861
[238]	valid_0's binary_logloss: 0.691881
[239]	valid_0's binary_logloss: 0.691898
[240]	valid_0's binary_logloss: 0.691918
[241]	valid_0's bin

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score

def get_clf_eval(y_test , pred):
    confusion = confusion_matrix( y_test, pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)
    roc_auc = roc_auc_score(y_test, pred)
    print('오차 행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f},\
    F1: {3:.4f}, AUC:{4:.4f}'.format(accuracy, precision, recall, f1, roc_auc))

In [8]:
get_clf_eval(y_test, preds)

오차 행렬
[[  0 218]
 [  0 269]]
정확도: 0.5524, 정밀도: 0.5524, 재현율: 1.0000,    F1: 0.7116, AUC:0.5000


# 찾아보니 lightGBM은 데이터 개수가 만개 이하이면 과적합의 문제가 발생-> 이에 다른 모델링 기법 적용

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [11]:
y_pred = classifier.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 29 189]
 [ 27 242]]
              precision    recall  f1-score   support

           0       0.52      0.13      0.21       218
           1       0.56      0.90      0.69       269

    accuracy                           0.56       487
   macro avg       0.54      0.52      0.45       487
weighted avg       0.54      0.56      0.48       487



In [14]:
get_clf_eval(y_test, y_pred)

오차 행렬
[[ 29 189]
 [ 27 242]]
정확도: 0.5565, 정밀도: 0.5615, 재현율: 0.8996,    F1: 0.6914, AUC:0.5163
