# 랜덤 포레스트로 분류

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

## market 데이터 변수 축소

In [2]:
import pandas as pd
import numpy as np

In [3]:
m=pd.read_csv('2019빅데이터페스티벌데이터/market_noDram_final.csv', encoding= 'euc_kr')

In [65]:
m

날짜  A등급 구리(현물)   니켈(현물)  알루미늄 99.7%(현물)   금괴(일간)  미국1년  미국3년  \
0     2001-01-02      1746.3   6935.0          1552.5   270.60  5.20  4.80   
1     2001-01-03      1716.8   6370.0          1515.5   267.50  5.10  4.90   
2     2001-01-04      1750.5   6569.0          1519.0   267.70  4.90  4.80   
3     2001-01-05      1740.3   6607.0          1527.5   268.20  4.60  4.60   
4     2001-01-08      1775.0   6734.0          1578.0   268.30  4.60  4.60   
5     2001-01-09      1783.3   6796.0          1572.3   267.40  4.70  4.70   
6     2001-01-10      1779.8   6947.0          1591.0   266.30  4.90  4.80   
7     2001-01-11      1795.0   7140.0          1597.5   263.90  4.90  4.80   
8     2001-01-12      1807.5   7325.0          1632.5   264.30  5.00  4.90   
9     2001-01-15      1800.8   7145.0          1626.0   263.60  5.18  5.05   
10    2001-01-16      1754.0   6995.0          1587.0   264.50  5.00  4.90   
11    2001-01-17      1776.0   7320.0          1609.0   263.60  4.90  4.80   
12    2001-01-18      1835.0   7415.0          1661.0   264.70  4.80  4.70   
13    2001-01-19      1823.0   7278.0          1648.5   264.60  4.80  4.80   
14    2001-01-22      1834.8   7265.0          1642.5   265.90  4.80  4.80   
15    2001-01-23      1828.0   7089.0          1659.0   266.20  4.90  4.80   
16    2001-01-24      1799.8   7080.0          1644.5   264.70  4.90  4.80   
17    2001-01-25      1801.5   7005.0          1661.0   264.70  4.90  4.80   
18    2001-01-26      1796.0   6720.0          1700.0   263.80  4.80  4.80   
19    2001-01-29      1781.5   6780.0          1686.0   263.00  4.80  4.80   
20    2001-01-30      1791.0   6935.0          1711.0   266.20  4.70  4.80   
21    2001-01-31      1799.8   7020.0          1716.0   265.20  4.60  4.70   
22    2001-02-01      1804.8   6845.0          1700.0   267.40  4.60  4.60   
23    2001-02-02      1795.0   6920.0          1687.0   267.20  4.70  4.70   
24    2001-02-05      1777.0   6850.0          1653.3   265.70  4.70  4.70   
25    2001-02-06      1774.0   6870.0          1620.0   263.30  4.70  4.80   
26    2001-02-07      1778.0   6900.0          1619.0   263.20  4.80  4.70   
27    2001-02-08      1779.5   6850.0          1642.5   263.10  4.70  4.80   
28    2001-02-09      1763.5   6490.0          1627.3   260.20  4.70  4.70   
29    2001-02-12      1761.0   6586.0          1618.0   261.50  4.70  4.70   
...          ...         ...      ...             ...      ...   ...   ...   
4665  2018-11-20      6206.0  11027.0          1929.3  1224.20  2.70  2.80   
4666  2018-11-21      6269.0  10951.5          1943.0  1226.60  2.70  2.90   
4667  2018-11-22      6286.3  10902.3          1936.8  1227.80  2.70  2.90   
4668  2018-11-23      6236.5  10849.0          1938.3  1223.20  2.70  2.80   
4669  2018-11-26      6221.0  10803.5          1940.5  1223.30  2.70  2.90   
4670  2018-11-27      6155.3  10700.0          1920.5  1213.20  2.70  2.90   
4671  2018-11-28      6244.0  10726.5          1924.8  1213.50  2.70  2.80   
4672  2018-11-29      6247.5  10984.0          1936.8  1227.40  2.70  2.80   
4673  2018-11-30      6227.0  11135.5          1957.3  1219.20  2.70  2.80   
4674  2018-12-03      6312.5  11179.5          1972.3  1234.20  2.70  2.80   
4675  2018-12-04      6212.5  11080.5          1972.5  1238.40  2.70  2.80   
4676  2018-12-05      6175.0  11156.0          1970.3  1237.80  2.70  2.80   
4677  2018-12-06      6079.5  10780.5          1937.0  1242.90  2.70  2.80   
4678  2018-12-07      6149.0  10845.5          1950.8  1245.80  2.70  2.70   
4679  2018-12-10      6088.5  10729.5          1928.8  1246.70  2.70  2.70   
4680  2018-12-11      6170.5  10696.5          1927.5  1244.20  2.70  2.80   
4681  2018-12-12      6144.8  10727.0          1922.0  1246.20  2.70  2.80   
4682  2018-12-13      6158.5  10780.5          1913.8  1242.70  2.70  2.80   
4683  2018-12-14      6127.8  11009.5          1908.3  1238.70  2.70  2.70   
4684  2018-12-17      6095.5  10907.

In [45]:
from sklearn.decomposition import PCA

pca=PCA(n_components=1)
m1=m[['A등급 구리(현물)','니켈(현물)','알루미늄 99.7%(현물)']]
#pd.DataFrame(ec_scaled).fillna(0, inplace=True)
m2=pca.fit(m1)
print('PCA component 별 변동성:', pca.explained_variance_ratio_)

PCA component 별 변동성: [0.95585305]


In [46]:
print(pca.components_.T)
pca.components_.T.shape

[[0.19241083]
 [0.98034117]
 [0.04369514]]


(3, 1)

In [48]:
m2.components_.T[0]

array([0.19241083])

In [24]:
m1_1= StandardScaler().fit_transform(m1)

m1_1=pd.DataFrame(m1_1)
m1_1.columns=['A등급 구리(현물)','니켈(현물)','알루미늄 99.7%(현물)']
m1_1.head()

A등급 구리(현물)    니켈(현물)  알루미늄 99.7%(현물)
0   -1.594937 -1.108757       -0.901840
1   -1.607458 -1.178171       -0.987416
2   -1.593155 -1.153723       -0.979321
3   -1.597484 -1.149054       -0.959662
4   -1.582756 -1.133451       -0.842862

In [25]:
m2_1=pca.fit(m1_1)
print('PCA component 별 변동성:', pca.explained_variance_ratio_)
print(pca.components_.T)
pca.components_.T.shape

PCA component 별 변동성: [0.83067367]
[[0.55586834]
 [0.57356545]
 [0.60169183]]


(3, 1)

In [49]:
m2pc=m2.components_.T.reshape(1,3)

In [59]:
금속=[]
for i in range(m1.shape[0]):
    a=m2pc[0,0]*m1.iloc[i,0]
    b=m2pc[0,1]*m1.iloc[i,1]
    c=m2pc[0,2]*m1.iloc[i,2]
    금속.append(a+b+c)


In [64]:
금속=pd.DataFrame(금속)
금속.head()

0
0  7202.509750
1  6641.324150
2  6843.049220
3  6878.711003
4  7012.097592

In [62]:
m['금속']=금속
m.head()

날짜  A등급 구리(현물)  니켈(현물)  알루미늄 99.7%(현물)  금괴(일간)  미국1년  미국3년  미국10년  \
0  2001-01-02      1746.3  6935.0          1552.5   270.6   5.2   4.8    4.9   
1  2001-01-03      1716.8  6370.0          1515.5   267.5   5.1   4.9    5.2   
2  2001-01-04      1750.5  6569.0          1519.0   267.7   4.9   4.8    5.0   
3  2001-01-05      1740.3  6607.0          1527.5   268.2   4.6   4.6    4.9   
4  2001-01-08      1775.0  6734.0          1578.0   268.3   4.6   4.6    4.9   

   국고채권(1년)  국고채권(3년)  국고채권(10년)  브랜트유 가격  원유 WTI           금속  
0       6.7       6.7        7.2     24.3    27.2  7202.509750  
1       6.6       6.6        7.2     25.0    28.0  6641.324150  
2       6.4       6.4        6.9     25.4    28.1  6843.049220  
3       6.2       6.2        6.7     25.2    28.0  6878.711003  
4       6.1       6.1        6.6     24.4    27.3  7012.097592

In [63]:
market=m.drop(m1,axis=1)

In [70]:
m_2=m[['미국1년','미국3년','미국10년']]
미국n년=[]
for i in range(m_2.shape[0]):
    a=(m_2.iloc[i,0]+m_2.iloc[i,1]+m_2.iloc[i,2])/3
    미국n년.append(a)

In [78]:
미국n년=pd.DataFrame(미국n년)
미국n년.head()
market['미국n년']=미국n년
market=market.drop(m_2,axis=1)

In [79]:
market.head()

날짜  금괴(일간)  국고채권(1년)  국고채권(3년)  국고채권(10년)  브랜트유 가격  원유 WTI  \
0  2001-01-02   270.6       6.7       6.7        7.2     24.3    27.2   
1  2001-01-03   267.5       6.6       6.6        7.2     25.0    28.0   
2  2001-01-04   267.7       6.4       6.4        6.9     25.4    28.1   
3  2001-01-05   268.2       6.2       6.2        6.7     25.2    28.0   
4  2001-01-08   268.3       6.1       6.1        6.6     24.4    27.3   

            금속      미국n년  
0  7202.509750  4.966667  
1  6641.324150  5.066667  
2  6843.049220  4.900000  
3  6878.711003  4.700000  
4  7012.097592  4.700000

In [82]:
m_3=m[['국고채권(1년)','국고채권(3년)','국고채권(10년)']]
국고채권n년=[]
for i in range(m_3.shape[0]):
    a=(m_3.iloc[i,0]+m_3.iloc[i,1]+m_3.iloc[i,2])/3
    국고채권n년.append(a)
국고채권n년=pd.DataFrame(국고채권n년)
market['국고채권(n년)']=국고채권n년
market=market.drop(m_3, axis=1)
market.head()

날짜  금괴(일간)  브랜트유 가격  원유 WTI           금속      미국n년  국고채권(n년)
0  2001-01-02   270.6     24.3    27.2  7202.509750  4.966667  6.866667
1  2001-01-03   267.5     25.0    28.0  6641.324150  5.066667  6.800000
2  2001-01-04   267.7     25.4    28.1  6843.049220  4.900000  6.566667
3  2001-01-05   268.2     25.2    28.0  6878.711003  4.700000  6.366667
4  2001-01-08   268.3     24.4    27.3  7012.097592  4.700000  6.266667

In [85]:
m_4=m[['브랜트유 가격','원유 WTI']]
oil=[]
for i in range(m_4.shape[0]):
    a=(m_4.iloc[i,0]+m_4.iloc[i,1])/2
    oil.append(a)
oil=pd.DataFrame(oil)
market['oil']=oil
market=market.drop(m_4, axis=1)
market.head()

날짜  금괴(일간)           금속      미국n년  국고채권(n년)    oil
0  2001-01-02   270.6  7202.509750  4.966667  6.866667  25.75
1  2001-01-03   267.5  6641.324150  5.066667  6.800000  26.50
2  2001-01-04   267.7  6843.049220  4.900000  6.566667  26.75
3  2001-01-05   268.2  6878.711003  4.700000  6.366667  26.60
4  2001-01-08   268.3  7012.097592  4.700000  6.266667  25.85

In [87]:
m2_=pca.fit(m_2)
print('PCA component 별 변동성:', pca.explained_variance_ratio_)
print(pca.components_.T)
pca.components_.T.shape
m_2pc=m2_.components_.T.reshape(1,3)

PCA component 별 변동성: [0.9335029]
[[0.66895425]
 [0.61128065]
 [0.42289027]]


In [92]:
미국n년=[]
for i in range(m_2.shape[0]):
    a=m_2pc[0,0]*m_2.iloc[i,0]
    b=m_2pc[0,1]*m_2.iloc[i,1]
    c=m_2pc[0,2]*m_2.iloc[i,2]
    미국n년.append(a+b+c)
미국n년=pd.DataFrame(미국n년)
market=market.drop('미국n년',axis=1)
market['미국n년']=미국n년

In [90]:
m3_=pca.fit(m_3)
print('PCA component 별 변동성:', pca.explained_variance_ratio_)
print(pca.components_.T)
pca.components_.T.shape
m_3pc=m3_.components_.T.reshape(1,3)

PCA component 별 변동성: [0.9702223]
[[0.54440254]
 [0.57661956]
 [0.60920912]]


In [93]:
국고=[]
for i in range(m_3.shape[0]):
    a=m_3pc[0,0]*m_3.iloc[i,0]
    b=m_3pc[0,1]*m_3.iloc[i,1]
    c=m_3pc[0,2]*m_3.iloc[i,2]
    국고.append(a+b+c)
국고=pd.DataFrame(국고)
market=market.drop('국고채권(n년)',axis=1)
market['국고채권(n년)']=국고

In [95]:
market=market.round(1)

날짜  금괴(일간)       금속   oil  미국n년  국고채권(n년)
0     2001-01-02   270.6   7202.5  25.8   8.5      11.9
1     2001-01-03   267.5   6641.3  26.5   8.6      11.8
2     2001-01-04   267.7   6843.0  26.8   8.3      11.4
3     2001-01-05   268.2   6878.7  26.6   8.0      11.0
4     2001-01-08   268.3   7012.1  25.8   8.0      10.9
5     2001-01-09   267.4   7074.2  26.1   8.1      10.9
6     2001-01-10   266.3   7222.4  27.4   8.4      10.9
7     2001-01-11   263.9   7414.8  27.5   8.4      10.7
8     2001-01-12   264.3   7600.1  28.0   8.5      10.7
9     2001-01-15   263.6   7422.1  28.3   8.8      10.7
10    2001-01-16   264.5   7264.3  28.2   8.5      10.6
11    2001-01-17   263.6   7588.1  27.2   8.4      10.5
12    2001-01-18   264.7   7694.9  27.7   8.2      10.5
13    2001-01-19   264.6   7557.7  29.6   8.3      10.5
14    2001-01-22   265.9   7547.0  29.4   8.3      10.5
15    2001-01-23   266.2   7373.9  29.0   8.5      10.2
16    2001-01-24   264.7   7359.0  28.8   8.5       9.2
17    2001-01-25   264.7   7286.5  29.0   8.5       7.3
18    2001-01-26   263.8   7007.7  28.4   8.4      10.6
19    2001-01-29   263.0   7063.2  27.8   8.4      10.6
20    2001-01-30   266.2   7218.0  28.0   8.3      10.5
21    2001-01-31   265.2   7303.3  27.7   8.1      10.3
22    2001-02-01   267.4   7132.0  29.0   8.0      10.3
23    2001-02-02   267.2   7203.1  30.2   8.2      10.2
24    2001-02-05   265.7   7129.5  29.6   8.2      10.1
25    2001-02-06   263.3   7147.1  29.6   8.3       9.9
26    2001-02-07   263.2   7177.2  30.6   8.3       9.8
27    2001-02-08   263.1   7129.5  30.7   8.2       9.9
28    2001-02-09   260.2   6772.8  30.2   8.1       9.7
29    2001-02-12   261.5   6866.1  29.8   8.1       9.3
...          ...     ...      ...   ...   ...       ...
4665  2018-11-20  1224.2  12088.6  57.9   4.8       3.5
4666  2018-11-21  1226.6  12027.3  59.0   4.9       3.5
4667  2018-11-22  1227.8  11982.2  58.6   4.9       3.5
4668  2018-11-23  1223.2  11920.4  54.8   4.8       3.4
4669  2018-11-26  1223.3  11872.9  56.0   4.9       3.4
4670  2018-11-27  1213.2  11757.9  56.2   4.9       3.4
4671  2018-11-28  1213.5  11801.1  54.4   4.8       3.4
4672  2018-11-29  1227.4  12054.8  55.4   4.8       3.4
4673  2018-11-30  1219.2  12200.3  54.8   4.8       3.4
4674  2018-12-03  1234.2  12260.5  57.4   4.8       3.4
4675  2018-12-04  1238.4  12144.2  57.3   4.7       3.4
4676  2018-12-05  1237.8  12210.9  57.2   4.7       3.4
4677  2018-12-06  1242.9  11823.0  55.9   4.7       3.2
4678  2018-12-07  1245.8  11900.7  57.0   4.7       3.2
4679  2018-12-10  1246.7  11774.3  55.4   4.7       3.2
4680  2018-12-11  1244.2  11757.7  56.1   4.7       3.2
4681  2018-12-12  1246.2  11782.4  55.7   4.7       3.2
4682  2018-12-13  1242.7  11837.2  57.2   4.7       3.2
4683  2018-12-14  1238.7  12055.5  55.8   4.7       3.2
4684  2018-12-17  1242.6  11950.8  54.3   4.7       3.2
4685  2018-12-18  1246.4  11768.9  51.2   4.5       3.2
4686  2018-12-19  1255.9  11891.2  51.9   4.5       3.1
4687  2018-12-20  1258.1  11852.7  50.3   4.5       3.1
4688  2018-12-21  1259.9  11815.3  49.6   4.5       3.2
4689  2018-12-24  1265.5  11812.9  46.5   4.5       3.2
4690  2018-12-25  1265.0  11812.9  46.6   4.5       3.2
4691  2018-12-26  1278.6  11812.9  50.6   4.5       3.1
4692  2018-12-27  1275.3  11692.8  48.8   4.4       3.1
4693  2018-12-28  1277.5  11670.8  48.8   4.4       3.1
4694  2018-12-31  1281.3  11622.1  49.8   4.4       3.1

[4695 rows x 6 columns]

In [96]:
market.to_csv('market_pca_final.csv', encoding='euc-kr')